export const state = {
  player: {
    x: 400,
    y: 300,
    radius: 18,
    angle: -Math.PI / 2,
    speed: 0,
    rotationSpeed: 0.08,
    thrust: 0.12,
    alive: true,
    cooldown: 0,
  },
  asteroids: [],
  bullets: [],
  keys: {
    ArrowUp: false,
    ArrowDown: false,
    ArrowLeft: false,
    ArrowRight: false,
    Space: false,
    KeyW: false,
    KeyA: false,
    KeyS: false,
    KeyD: false,
  },
  game: {
    width: 800,
    height: 600,
    score: 0,
    lives: 3,
    over: false,
    spawnTimer: 0,
  },
  effects: {
    particles: [],
  },
};
